import type { Metadata } from "next";
import { DM_Sans, Russo_One } from "next/font/google";
import "./globals.css";
import HeroPage from "./hero/page";
import Footer from "@/components/Footer";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const russoOne = Russo_One({
  variable: "--font-russo-one",
  subsets: ["latin"],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${russoOne.variable} antialiased p-1`}
      >
        <HeroPage/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
